### ISSUE TITLE
Another hosting provider

### ISSUE THREAD

**Issue by mynameisbob1928** [discordjs/resource-webhooks#57]
Pylexnodes is another bot hosting provider that can be added into the affordable hosting providers list, we have free and paid plans.
It would be amazing if Pylex could be added to the list.
[discord](https://discord.gg/pylex)
[store](https://store.pylexnodes.net)
[main page](https://pylexnodes.net)

**Comment by almostSouji** [comment]
Thanks for the suggestion. We are not interested in adding these type of resale offers to our resources.
